version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: clementgalzi/nodejs:latest
    steps:
      - checkout
      - run: docker build -t clementgalzi/nodejs
workflows:
  build_and_test:
    jobs:
      - build

