version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    environment: 
      IMG_NAME: clementgalzi/nodejs
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker build -t $IMG_NAME:latest .
      - run: docker run --rm -d --name=test -p 8080:8080 $IMG_NAME:latest && sleep 10 && curl http://0.0.0.0:8080/ ; docker stop test
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && docker push $IMAGE_NAME:latest
workflows:
  build_and_test:
    jobs:
      - build
