version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run: docker build -t clementgalzi/nodejs:latest
workflows:
  build_and_test:
    jobs:
      - build

