version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    environment: 
      IMG_NAME: clementgalzi/nodejs
    docker:
            - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMG_NAME:latest .
workflows:
  build_and_test:
    jobs:
      - build

